name: Daily Node.js Script

on:
  schedule:
  - cron: '0 0,2,4,6,8 * * *'  # Every 2 hours from 12 AM to 8 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version here

    - name: Install dependencies
      run: npm install

    - name: Run Penyedia Node.js script
      run: node Penyedia_Terumumkan_TahunLama.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_PEN: ${{ secrets.API_URL_PENLM }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Penyedia Node.js script
      run: node Penyedia_Terumumkan_TahunBaru.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_PEN: ${{ secrets.API_URL_PENBR }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Swakelola Node.js script
      run: node Swakelola_Terumumkan.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_SWA: ${{ secrets.API_URL_SWA }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Instansi Satker Node.js script
      run: node InstansiSatker.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_IS: ${{ secrets.API_URL_IS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Tender Selesai Node.js script
      run: node Tender_Selesai.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_TS: ${{ secrets.API_URL_TS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Tender Selesai Nilai Node.js script
      run: node Tender_Selesai_Nilai.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_TSN: ${{ secrets.API_URL_TSN }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Tender Selesai Pengumuman Node.js script
      run: node Tender_Selesai_Pengumuman.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_TSP: ${{ secrets.API_URL_TSP }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Non Tender Selesai Node.js script
      run: node NonTender_Selesai.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_NTS: ${{ secrets.API_URL_NTS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Pencatatan Non Tender Node.js script
      run: node Pencatatan_NonTender.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_PNT: ${{ secrets.API_URL_PNT }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run Pencatatan Swakelola Node.js script
      run: node Pencatatan_Swakelola.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_PS: ${{ secrets.API_URL_PS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run E-Purchasing Node.js script
      run: node E-Purchasing.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_EP: ${{ secrets.API_URL_EP }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Run TokoDaring Node.js script
      run: node TokoDaring.js
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_TD: ${{ secrets.API_URL_TD }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
